.MAKEFLAGS: -I${../../share:L:tA}

IMPORT_URL = ftp://ftp2.freebsd.org/pub/FreeBSD/releases/amd64/amd64/10.1-RELEASE/base.txz
IMPORT_SHA256 = 2b028a894d25711ad496762622a52d74b1e32ee04693ad1cf056e3ddcdc23975
IMPORT_MANIFEST = manifest.json

.include "jetpack.image.mk"
