#!/bin/sh
set -e

rootdir="$(dirname "$(realpath "$0")")"
revision="$(cd "$rootdir" ; if test -e .git ; then git describe --always --long --dirty='*' ; else echo '?' ; fi)"
exec "${rootdir}/bin/jetpack" \
     -config="${rootdir}/jetpack.conf" \
     -o="path.libexec=${rootdir}/bin" \
     -o="path.share=${rootdir}/share" \
     -o="version.git=$revision" \
     "${@}"
