IMPORT_URL = ftp://ftp.de.freebsd.org/pub/FreeBSD/snapshots/amd64/amd64/11.0-CURRENT/base.txz
IMPORT_MANIFEST = manifest.json

.include <${.jetpack.image.mk:U${${JETPACK:Ujetpack} config path.share:L:sh}/jetpack.image.mk}>
