---
 - hosts: default
   tasks:
   - include: tasks/dependencies.yml # install git & go
   - include: tasks/networking.yml   # setup and start lo1
   - include: tasks/pf.yml           # configure and start firewall

   - name: copy Jetpack source
     command: "{{ item }}"
     with_items:
     - "rm -rf /usr/local/src/jetpack"
     - "install -d /usr/local/src"
     - "cp -R /vagrant /usr/local/src/jetpack"

   - name: build & install Jetpack
     command: "{{ item }} PREFIX=/usr/local"
     args:
       chdir: "/usr/local/src/jetpack"
     with_items:
     - "make"
     - "make install"

   - name: add group
     user: name=_jetpack system=yes

   - name: add user
     user: name=_jetpack group=_jetpack createhome=no home=/var/jetpack shell=/usr/sbin/nologin system=yes
   
   - name: init Jetpack
     command: "jetpack init"

   handlers:
    - name: restart pf
      service: name=pf state=restarted
