---
 - hosts: default
   tasks:
   - include: tasks/dependencies.yml # install git & go
   - include: tasks/networking.yml   # setup and start lo1
   - include: tasks/pf.yml           # configure and start firewall

   - name: copy Jetpack source
     command: "{{ item }}"
     with_items:
     - "rm -rf /usr/local/src/jetpack"
     - "install -d /usr/local/src"
     - "cp -R /vagrant /usr/local/src/jetpack"

   - name: build & install Jetpack
     command: "{{ item }} PREFIX=/usr/local"
     args:
       chdir: "/usr/local/src/jetpack"
     with_items:
     - "make"
     - "make install"

   - name: add group
     user: name=_jetpack system=yes

   - name: add user
     user: name=_jetpack group=_jetpack createhome=no home=/var/jetpack shell=/usr/sbin/nologin system=yes

   - name: generate signing key
     command: "openssl rand -hex 32"
     register: jetpack_mds_signing_key

   - name: write jetpack.conf
     template: src=usr/local/etc/jetpack.conf.j2 dest=/usr/local/etc/jetpack.conf owner=root group=_jetpack mode=0640
   
   - name: init Jetpack
     command: "jetpack init"

   - name: configure metadata service
     lineinfile: dest=/etc/rc.local state=present line='/usr/local/bin/jetpack mds -p /var/run/jetpack.mds.pid'
     notify:
       - start mds

   handlers:
    - name: restart pf
      service: name=pf state=restarted
    - name: start mds
      command: "jetpack mds -p /var/run/jetpack.mds.pid"
