---
 - name: update packages
   command: "pkg update"
 
 - name: upgrade pkg
   command: "pkg install -f -y pkg"
 
 - name: ensure dependencies are installed.
   pkgng: name={{item}} state=present cached=no
   with_items:
   - git
   - lang/go

 - name: install gb
   command: "/usr/bin/env GOBIN=/usr/local/bin GOPATH=/usr/local/site-go go get github.com/constabulary/gb/..."
   args:
     creates: /usr/local/bin/gb
